# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sand/sandreco-experimental

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sand/sandreco-experimental

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sand/sandreco-experimental/CMakeFiles /home/sand/sandreco-experimental//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sand/sandreco-experimental/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named format-check

# Build rule for target.
format-check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format-check
.PHONY : format-check

# fast build rule for target.
format-check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format-check.dir/build.make CMakeFiles/format-check.dir/build
.PHONY : format-check/fast

#=============================================================================
# Target rules for targets named sandreco

# Build rule for target.
sandreco: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sandreco
.PHONY : sandreco

# fast build rule for target.
sandreco/fast:
	$(MAKE) $(MAKESILENT) -f include/CMakeFiles/sandreco.dir/build.make include/CMakeFiles/sandreco.dir/build
.PHONY : sandreco/fast

#=============================================================================
# Target rules for targets named sand_caf_caf_streamer

# Build rule for target.
sand_caf_caf_streamer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_caf_caf_streamer
.PHONY : sand_caf_caf_streamer

# fast build rule for target.
sand_caf_caf_streamer/fast:
	$(MAKE) $(MAKESILENT) -f src/streamers/caf_streamer/CMakeFiles/sand_caf_caf_streamer.dir/build.make src/streamers/caf_streamer/CMakeFiles/sand_caf_caf_streamer.dir/build
.PHONY : sand_caf_caf_streamer/fast

#=============================================================================
# Target rules for targets named sand_caf_caf_streamer_dictionaries

# Build rule for target.
sand_caf_caf_streamer_dictionaries: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_caf_caf_streamer_dictionaries
.PHONY : sand_caf_caf_streamer_dictionaries

# fast build rule for target.
sand_caf_caf_streamer_dictionaries/fast:
	$(MAKE) $(MAKESILENT) -f src/streamers/caf_streamer/CMakeFiles/sand_caf_caf_streamer_dictionaries.dir/build.make src/streamers/caf_streamer/CMakeFiles/sand_caf_caf_streamer_dictionaries.dir/build
.PHONY : sand_caf_caf_streamer_dictionaries/fast

#=============================================================================
# Target rules for targets named sand_png_png_streamer

# Build rule for target.
sand_png_png_streamer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_png_png_streamer
.PHONY : sand_png_png_streamer

# fast build rule for target.
sand_png_png_streamer/fast:
	$(MAKE) $(MAKESILENT) -f src/streamers/png/CMakeFiles/sand_png_png_streamer.dir/build.make src/streamers/png/CMakeFiles/sand_png_png_streamer.dir/build
.PHONY : sand_png_png_streamer/fast

#=============================================================================
# Target rules for targets named sand_root_tree_streamer

# Build rule for target.
sand_root_tree_streamer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_root_tree_streamer
.PHONY : sand_root_tree_streamer

# fast build rule for target.
sand_root_tree_streamer/fast:
	$(MAKE) $(MAKESILENT) -f src/streamers/root/CMakeFiles/sand_root_tree_streamer.dir/build.make src/streamers/root/CMakeFiles/sand_root_tree_streamer.dir/build
.PHONY : sand_root_tree_streamer/fast

#=============================================================================
# Target rules for targets named sand_root_tree_streamer_dictionaries

# Build rule for target.
sand_root_tree_streamer_dictionaries: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_root_tree_streamer_dictionaries
.PHONY : sand_root_tree_streamer_dictionaries

# fast build rule for target.
sand_root_tree_streamer_dictionaries/fast:
	$(MAKE) $(MAKESILENT) -f src/streamers/root/CMakeFiles/sand_root_tree_streamer_dictionaries.dir/build.make src/streamers/root/CMakeFiles/sand_root_tree_streamer_dictionaries.dir/build
.PHONY : sand_root_tree_streamer_dictionaries/fast

#=============================================================================
# Target rules for targets named sand_grain_geant_gdml_parser

# Build rule for target.
sand_grain_geant_gdml_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_grain_geant_gdml_parser
.PHONY : sand_grain_geant_gdml_parser

# fast build rule for target.
sand_grain_geant_gdml_parser/fast:
	$(MAKE) $(MAKESILENT) -f src/data/grain/geant_gdml_parser/CMakeFiles/sand_grain_geant_gdml_parser.dir/build.make src/data/grain/geant_gdml_parser/CMakeFiles/sand_grain_geant_gdml_parser.dir/build
.PHONY : sand_grain_geant_gdml_parser/fast

#=============================================================================
# Target rules for targets named sand_grain_geant_run_manager

# Build rule for target.
sand_grain_geant_run_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_grain_geant_run_manager
.PHONY : sand_grain_geant_run_manager

# fast build rule for target.
sand_grain_geant_run_manager/fast:
	$(MAKE) $(MAKESILENT) -f src/data/grain/geant_run_manager/CMakeFiles/sand_grain_geant_run_manager.dir/build.make src/data/grain/geant_run_manager/CMakeFiles/sand_grain_geant_run_manager.dir/build
.PHONY : sand_grain_geant_run_manager/fast

#=============================================================================
# Target rules for targets named sand_edep_reader

# Build rule for target.
sand_edep_reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_edep_reader
.PHONY : sand_edep_reader

# fast build rule for target.
sand_edep_reader/fast:
	$(MAKE) $(MAKESILENT) -f src/data/common/edep_reader/CMakeFiles/sand_edep_reader.dir/build.make src/data/common/edep_reader/CMakeFiles/sand_edep_reader.dir/build
.PHONY : sand_edep_reader/fast

#=============================================================================
# Target rules for targets named sand_genie_reader

# Build rule for target.
sand_genie_reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_genie_reader
.PHONY : sand_genie_reader

# fast build rule for target.
sand_genie_reader/fast:
	$(MAKE) $(MAKESILENT) -f src/data/common/genie_reader/CMakeFiles/sand_genie_reader.dir/build.make src/data/common/genie_reader/CMakeFiles/sand_genie_reader.dir/build
.PHONY : sand_genie_reader/fast

#=============================================================================
# Target rules for targets named sand_geoinfo

# Build rule for target.
sand_geoinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_geoinfo
.PHONY : sand_geoinfo

# fast build rule for target.
sand_geoinfo/fast:
	$(MAKE) $(MAKESILENT) -f src/data/common/geoinfo/CMakeFiles/sand_geoinfo.dir/build.make src/data/common/geoinfo/CMakeFiles/sand_geoinfo.dir/build
.PHONY : sand_geoinfo/fast

#=============================================================================
# Target rules for targets named sand_hdf5

# Build rule for target.
sand_hdf5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_hdf5
.PHONY : sand_hdf5

# fast build rule for target.
sand_hdf5/fast:
	$(MAKE) $(MAKESILENT) -f src/data/common/hdf5/CMakeFiles/sand_hdf5.dir/build.make src/data/common/hdf5/CMakeFiles/sand_hdf5.dir/build
.PHONY : sand_hdf5/fast

#=============================================================================
# Target rules for targets named sand_cl

# Build rule for target.
sand_cl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_cl
.PHONY : sand_cl

# fast build rule for target.
sand_cl/fast:
	$(MAKE) $(MAKESILENT) -f src/data/common/ocl/CMakeFiles/sand_cl.dir/build.make src/data/common/ocl/CMakeFiles/sand_cl.dir/build
.PHONY : sand_cl/fast

#=============================================================================
# Target rules for targets named sand_root_tgeomanager

# Build rule for target.
sand_root_tgeomanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_root_tgeomanager
.PHONY : sand_root_tgeomanager

# fast build rule for target.
sand_root_tgeomanager/fast:
	$(MAKE) $(MAKESILENT) -f src/data/common/root_tgeomanager/CMakeFiles/sand_root_tgeomanager.dir/build.make src/data/common/root_tgeomanager/CMakeFiles/sand_root_tgeomanager.dir/build
.PHONY : sand_root_tgeomanager/fast

#=============================================================================
# Target rules for targets named sand_common_geoinfo_test

# Build rule for target.
sand_common_geoinfo_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_common_geoinfo_test
.PHONY : sand_common_geoinfo_test

# fast build rule for target.
sand_common_geoinfo_test/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/common/geoinfo_test/CMakeFiles/sand_common_geoinfo_test.dir/build.make src/processes/common/geoinfo_test/CMakeFiles/sand_common_geoinfo_test.dir/build
.PHONY : sand_common_geoinfo_test/fast

#=============================================================================
# Target rules for targets named sand_common_genie_reader_test

# Build rule for target.
sand_common_genie_reader_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_common_genie_reader_test
.PHONY : sand_common_genie_reader_test

# fast build rule for target.
sand_common_genie_reader_test/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/common/genie_reader_test/CMakeFiles/sand_common_genie_reader_test.dir/build.make src/processes/common/genie_reader_test/CMakeFiles/sand_common_genie_reader_test.dir/build
.PHONY : sand_common_genie_reader_test/fast

#=============================================================================
# Target rules for targets named sand_fake_reco

# Build rule for target.
sand_fake_reco: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_fake_reco
.PHONY : sand_fake_reco

# fast build rule for target.
sand_fake_reco/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/fake_reco/CMakeFiles/sand_fake_reco.dir/build.make src/processes/fake_reco/CMakeFiles/sand_fake_reco.dir/build
.PHONY : sand_fake_reco/fast

#=============================================================================
# Target rules for targets named sand_grain_optical_simulation

# Build rule for target.
sand_grain_optical_simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_grain_optical_simulation
.PHONY : sand_grain_optical_simulation

# fast build rule for target.
sand_grain_optical_simulation/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/grain/optical_simulation/CMakeFiles/sand_grain_optical_simulation.dir/build.make src/processes/grain/optical_simulation/CMakeFiles/sand_grain_optical_simulation.dir/build
.PHONY : sand_grain_optical_simulation/fast

#=============================================================================
# Target rules for targets named sand_grain_detector_response_fast

# Build rule for target.
sand_grain_detector_response_fast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_grain_detector_response_fast
.PHONY : sand_grain_detector_response_fast

# fast build rule for target.
sand_grain_detector_response_fast/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/grain/detector_response_fast/CMakeFiles/sand_grain_detector_response_fast.dir/build.make src/processes/grain/detector_response_fast/CMakeFiles/sand_grain_detector_response_fast.dir/build
.PHONY : sand_grain_detector_response_fast/fast

#=============================================================================
# Target rules for targets named sand_grain_spill_slicer

# Build rule for target.
sand_grain_spill_slicer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_grain_spill_slicer
.PHONY : sand_grain_spill_slicer

# fast build rule for target.
sand_grain_spill_slicer/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/grain/spill_slicer/CMakeFiles/sand_grain_spill_slicer.dir/build.make src/processes/grain/spill_slicer/CMakeFiles/sand_grain_spill_slicer.dir/build
.PHONY : sand_grain_spill_slicer/fast

#=============================================================================
# Target rules for targets named sand_grain_mask_weights_computation

# Build rule for target.
sand_grain_mask_weights_computation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_grain_mask_weights_computation
.PHONY : sand_grain_mask_weights_computation

# fast build rule for target.
sand_grain_mask_weights_computation/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/grain/mask_weights_computation/CMakeFiles/sand_grain_mask_weights_computation.dir/build.make src/processes/grain/mask_weights_computation/CMakeFiles/sand_grain_mask_weights_computation.dir/build
.PHONY : sand_grain_mask_weights_computation/fast

#=============================================================================
# Target rules for targets named sand_stt_stt_fast_digi

# Build rule for target.
sand_stt_stt_fast_digi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_stt_stt_fast_digi
.PHONY : sand_stt_stt_fast_digi

# fast build rule for target.
sand_stt_stt_fast_digi/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/stt/fast_digi/CMakeFiles/sand_stt_stt_fast_digi.dir/build.make src/processes/stt/fast_digi/CMakeFiles/sand_stt_stt_fast_digi.dir/build
.PHONY : sand_stt_stt_fast_digi/fast

#=============================================================================
# Target rules for targets named sand_drift_drift_fast_digi

# Build rule for target.
sand_drift_drift_fast_digi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_drift_drift_fast_digi
.PHONY : sand_drift_drift_fast_digi

# fast build rule for target.
sand_drift_drift_fast_digi/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/drift/fast_digi/CMakeFiles/sand_drift_drift_fast_digi.dir/build.make src/processes/drift/fast_digi/CMakeFiles/sand_drift_drift_fast_digi.dir/build
.PHONY : sand_drift_drift_fast_digi/fast

#=============================================================================
# Target rules for targets named sand_tracker_clustering

# Build rule for target.
sand_tracker_clustering: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_tracker_clustering
.PHONY : sand_tracker_clustering

# fast build rule for target.
sand_tracker_clustering/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/tracker/clustering/CMakeFiles/sand_tracker_clustering.dir/build.make src/processes/tracker/clustering/CMakeFiles/sand_tracker_clustering.dir/build
.PHONY : sand_tracker_clustering/fast

#=============================================================================
# Target rules for targets named sand_ecal_optical_simulation

# Build rule for target.
sand_ecal_optical_simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_ecal_optical_simulation
.PHONY : sand_ecal_optical_simulation

# fast build rule for target.
sand_ecal_optical_simulation/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/ecal/optical_simulation/CMakeFiles/sand_ecal_optical_simulation.dir/build.make src/processes/ecal/optical_simulation/CMakeFiles/sand_ecal_optical_simulation.dir/build
.PHONY : sand_ecal_optical_simulation/fast

#=============================================================================
# Target rules for targets named sand_ecal_fast_digi

# Build rule for target.
sand_ecal_fast_digi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_ecal_fast_digi
.PHONY : sand_ecal_fast_digi

# fast build rule for target.
sand_ecal_fast_digi/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/ecal/fast_digi/CMakeFiles/sand_ecal_fast_digi.dir/build.make src/processes/ecal/fast_digi/CMakeFiles/sand_ecal_fast_digi.dir/build
.PHONY : sand_ecal_fast_digi/fast

#=============================================================================
# Target rules for targets named sand_ecal_spill_slicer_placeholder

# Build rule for target.
sand_ecal_spill_slicer_placeholder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sand_ecal_spill_slicer_placeholder
.PHONY : sand_ecal_spill_slicer_placeholder

# fast build rule for target.
sand_ecal_spill_slicer_placeholder/fast:
	$(MAKE) $(MAKESILENT) -f src/processes/ecal/spill_slicer_placeholder/CMakeFiles/sand_ecal_spill_slicer_placeholder.dir/build.make src/processes/ecal/spill_slicer_placeholder/CMakeFiles/sand_ecal_spill_slicer_placeholder.dir/build
.PHONY : sand_ecal_spill_slicer_placeholder/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... format"
	@echo "... format-check"
	@echo "... sand_caf_caf_streamer"
	@echo "... sand_caf_caf_streamer_dictionaries"
	@echo "... sand_cl"
	@echo "... sand_common_genie_reader_test"
	@echo "... sand_common_geoinfo_test"
	@echo "... sand_drift_drift_fast_digi"
	@echo "... sand_ecal_fast_digi"
	@echo "... sand_ecal_optical_simulation"
	@echo "... sand_ecal_spill_slicer_placeholder"
	@echo "... sand_edep_reader"
	@echo "... sand_fake_reco"
	@echo "... sand_genie_reader"
	@echo "... sand_geoinfo"
	@echo "... sand_grain_detector_response_fast"
	@echo "... sand_grain_geant_gdml_parser"
	@echo "... sand_grain_geant_run_manager"
	@echo "... sand_grain_mask_weights_computation"
	@echo "... sand_grain_optical_simulation"
	@echo "... sand_grain_spill_slicer"
	@echo "... sand_hdf5"
	@echo "... sand_png_png_streamer"
	@echo "... sand_root_tgeomanager"
	@echo "... sand_root_tree_streamer"
	@echo "... sand_root_tree_streamer_dictionaries"
	@echo "... sand_stt_stt_fast_digi"
	@echo "... sand_tracker_clustering"
	@echo "... sandreco"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

