/* This file is auto generated by cmake: DO NOT EDIT */
#ifndef UFW_IMPLEMENT_STREAMER_FOR_TYPE
#define UFW_IMPLEMENT_STREAMER_FOR_TYPE(T)
#endif
#include <ufw/data.hpp>
#include <caf/caf_wrapper.hpp>
#include <common/cluster.h>
#include <common/digi.h>
#include <common/hit.h>
#include <common/sand.h>
#include <common/timerange.h>
#include <common/truth.h>
#include <common/utils/list.h>
#include <ecal/digit.h>
#include <ecal/photo_electron.h>
#include <ecal/slice.h>
#include <grain/digi.h>
#include <grain/grain.h>
#include <grain/image.h>
#include <grain/photons.h>
#include <tracker/cluster_container.h>
#include <tracker/digi.h>
