/* This file is auto generated by cmake: DO NOT EDIT */
#ifdef __CLING__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;
#pragma link C++ class ufw::context_id+;
#pragma link C++ class ufw::data::data_base+;
#pragma link C++ class ufw::data::managed_tag+;
#pragma link C++ class ufw::data::instanced_tag+;
#pragma link C++ class ufw::data::context_tag+;
#pragma link C++ class ufw::data::base<ufw::data::managed_tag,ufw::data::instanced_tag,ufw::data::context_tag>+;
#pragma link C++ class sand::truth+;
#pragma link C++ class sand::geo_id+;
#pragma link C++ class sand::channel_id+;
#pragma link C++ class sand::caf::caf_wrapper+;
#pragma link C++ class sand::ecal::digits_container+;
#pragma link C++ class sand::ecal::pes_container+;
#pragma link C++ class sand::ecal::slices_container+;
#pragma link C++ class sand::grain::digi+;
#pragma link C++ class sand::grain::images+;
#pragma link C++ class sand::grain::hits+;
#pragma link C++ class sand::tracker::cluster_container+;
#pragma link C++ class sand::tracker::digi+;
#endif
