/* This file is auto generated by cmake: DO NOT EDIT */
#ifdef __CLING__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;
#pragma link C++ class ufw::data::data_base+;
#pragma link C++ class ufw::data::managed_tag+;
#pragma link C++ class ufw::data::instanced_tag+;
#pragma link C++ class ufw::data::context_tag+;
#pragma link C++ class ufw::data::base<ufw::data::managed_tag,ufw::data::instanced_tag,ufw::data::context_tag>+;
#pragma link C++ class sand::true_hit+;
#pragma link C++ class sand::true_hits+;
#pragma link C++ class sand::example1+;
#pragma link C++ class sand::example2+;
#pragma link C++ class sand::grain::digi+;
#pragma link C++ class sand::grain::hits+;
#endif
