/* This file is auto generated by cmake: DO NOT EDIT */
#ifndef UFW_IMPLEMENT_STREAMER_FOR_TYPE
#define UFW_IMPLEMENT_STREAMER_FOR_TYPE(T)
#endif
#include <ufw/data.hpp>
#include <common/sand.h>
#include <common/truth.h>
#include <example1.h>
#include <example2.h>
#include <grain/digi.h>
#include <grain/photons.h>
#include <grain/picture.h>
