//
// Created by paolo on 08/05/2025.
//

#include <ufw/factory.hpp>

#include <edep_reader/edep_reader.hpp>

#include "fake_reco.hpp"

namespace sand::fake_reco {
  fake_reco::fake_reco(): process{{}, {}} {}

  void fake_reco::configure(const ufw::config &cfg) {
    process::configure(cfg);
  }

  void fake_reco::run() {
    const auto &inputTree = get<edep_reader>();

    std::size_t childrenTrajectoriesCount = inputTree.GetChildrenTrajectories().size();

    UFW_DEBUG("Reading root trajectory with id: {}", inputTree.GetId());
    UFW_DEBUG("Children trajectories foud: {}", childrenTrajectoriesCount);

    for (int i = 0; i < childrenTrajectoriesCount; ++i) {
      const auto &childTrajectory = inputTree.GetChildrenTrajectories()[i];
      UFW_DEBUG("Parsing children trajectory number {}", i);

      UFW_DEBUG("Children trajectory id: {}", childTrajectory.GetId());
      UFW_DEBUG("Interaction number: {}", childTrajectory.GetInteractionNumber());
      UFW_DEBUG("Reaction generated by the child trajectory: {}", childTrajectory.GetReaction());
    }
  }
} // namespace sand::fake_reco

UFW_REGISTER_DYNAMIC_PROCESS_FACTORY(sand::fake_reco::fake_reco);
