//
// Created by paolo on 08/05/2025.
//

#include <ufw/factory.hpp>

#include "caf_handlers/interactions.hpp"
#include "caf_handlers/particles.hpp"

#include <duneanaobj/StandardRecord/StandardRecord.h>
// #include <duneanaobj/StandardRecord/SRTrueParticle.h>
// #include <duneanaobj/StandardRecord/SRRecoParticle.h>

#include <edep_reader/edep_reader.hpp>

#include "fake_reco.hpp"

namespace sand::fake_reco {

fake_reco::fake_reco() : process{{}, {}} {}

void fake_reco::configure(const ufw::config& cfg) { process::configure(cfg); }

void fake_reco::run() {
    // Read input
    const auto& inputTree = get<edep_reader>();

    // Just logging some values
    [[maybe_unused]] std::size_t childrenTrajectoriesCount =
        inputTree.GetChildrenTrajectories().size();

    UFW_DEBUG("Reading root trajectory with id: {}", inputTree.GetId());
    UFW_DEBUG("Children trajectories foud: {}", childrenTrajectoriesCount);

    // Create empty interactions
    caf::SRTrueInteraction true_interaction{};
    caf::SRInteraction reco_interaction =
        empty_interaction_from_vertex(inputTree);

    [[maybe_unused]] size_t particle_number = 0;
    // Fill the interactions
    for (const auto& particle : inputTree) {
        UFW_DEBUG("Parsing particle number {}", particle_number++);

        caf::SRRecoParticle recoParticle =
            reco_particle_from_edep_trajectory(particle);
        fill_sr_interaction(reco_interaction, recoParticle);

        caf::SRTrueParticle true_particle =
            true_particle_from_edep_trajectory(particle);
        fill_sr_true_interaction(true_interaction, true_particle);

        UFW_DEBUG("Children trajectory id: {}", particle.GetId());
        UFW_DEBUG("Children trajectory PDG code: {}", particle.GetPDGCode());
        UFW_DEBUG("Interaction number: {}", particle.GetInteractionNumber());
        UFW_DEBUG("Reaction generated by the child trajectory: {}",
                  particle.GetReaction());
    }
}
} // namespace sand::fake_reco

UFW_REGISTER_DYNAMIC_PROCESS_FACTORY(sand::fake_reco::fake_reco);
