//
// Created by paolo on 08/05/2025.
//

#include "fake_reco.hpp"

#include "caf_handlers/interactions.hpp"
#include "caf_handlers/particles.hpp"

#include <edep_reader/edep_reader.hpp>
#include <genie_reader/genie_reader.hpp>

#include <ufw/factory.hpp>

#include <duneanaobj/StandardRecord/StandardRecord.h>

namespace sand::fake_reco {
  fake_reco::fake_reco() : process{{}, {}} {}

  void fake_reco::configure(const ufw::config& cfg) { process::configure(cfg); }

  void fake_reco::run() {
    // Read input
    const auto& edep  = get<edep_reader>();
    const auto& genie = get<genie_reader>();

    const auto& event            = edep.event();
    const auto& primary_vertices = event.Primaries;

    // Initialize spill structures
    caf::StandardRecord standard_record{};

    auto& truth_branch             = standard_record.mc;
    auto& true_interactions_vector = truth_branch.nu;
    true_interactions_vector.reserve(primary_vertices.size());
    truth_branch.nnu = primary_vertices.size();

    auto& reco_branch                       = standard_record.nd.sand;
    auto& reconstructed_interactions_vector = reco_branch.ixn;
    reconstructed_interactions_vector.reserve(primary_vertices.size());
    reco_branch.nixn = primary_vertices.size();

    for (std::size_t event_index = 0; event_index < primary_vertices.size(); event_index++) {
      const auto& vertex = primary_vertices[event_index];
      UFW_DEBUG("Processing vertex number {} that points to gRooTracker index: {}", &vertex - primary_vertices.data(),
                vertex.InteractionNumber);
      // Create empty interactions
      caf::SRTrueInteraction& true_interaction = true_interactions_vector.emplace_back();
      caf::SRInteraction reco_interaction      = empty_interaction_from_vertex(edep);

      initialize_SRTrueInteraction(true_interaction, genie.events_[event_index], genie.stdHeps_[event_index]);

      // Fill the interactions
      for (const auto& particle : edep) {
        caf::SRRecoParticle recoParticle = reco_particle_from_edep_trajectory(particle);
        fill_sr_interaction(reco_interaction, recoParticle);

        caf::SRTrueParticle true_particle = true_particle_from_edep_trajectory(particle);
        fill_sr_true_interaction(true_interaction, true_particle);

        // UFW_DEBUG("Children trajectory id: {}", particle.GetId());
        // UFW_DEBUG("Children trajectory PDG code: {}", particle.GetPDGCode());
        // UFW_DEBUG("Interaction number: {}", particle.GetInteractionNumber());
        // UFW_DEBUG("Reaction generated by the child trajectory: {}",
        //           particle.GetReaction());
      }
    }

    UFW_ASSERT(true_interactions_vector.size() == truth_branch.nnu,
               "truth_branch.nnu doesn't match truth_branch.nu size");
    UFW_ASSERT(reconstructed_interactions_vector.size() == reco_branch.nixn,
               "reco_branch.nixn doesn't match reco_branch.ixn size");
  }
} // namespace sand::fake_reco

UFW_REGISTER_DYNAMIC_PROCESS_FACTORY(sand::fake_reco::fake_reco);
